import Head from "next/head";
// import Image from "next/image";
import { useState } from "react";
import ChatList from "../components/Chat/ChatList";
import OpenBox from "../components/OpenBox";
import QButton from "../components/QButton";
import TaskList from "../components/Task/TaskList";

type QuickButtonStatus = "none" | "quick" | "inbox" | "task";

export default function Home() {
    const [quickStatus, setQuickStatus] = useState<QuickButtonStatus>("none");

    const setActiveState = () => {
        if (quickStatus === "none") {
            setQuickStatus("quick");
        } else if (quickStatus === "quick") {
            setQuickStatus("none");
        }
    };

    const inboxOnclick = () => {
        if (quickStatus === "quick") {
            setQuickStatus("inbox");
        } else if (quickStatus === "inbox") {
            setQuickStatus("quick");
        } else if (quickStatus === "task") {
            setQuickStatus("inbox");
        }
    };

    const taskOnclick = () => {
        if (quickStatus === "quick") {
            setQuickStatus("task");
        } else if (quickStatus === "task") {
            setQuickStatus("quick");
        } else if (quickStatus === "inbox") {
            setQuickStatus("task");
        }
    };

    return (
        <div data-theme="dark">
            <Head>
                <title>Quicks</title>
                <meta
                    name="Quicks App"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={"flex flex-row h-screen w-full"}>
                <div className="w-1/5 border-r-2 border-slate-400"></div>
                <div className="flex-auto">
                    <div className="flex flex-row bg-slate-700 h-fit items-center">
                        <svg
                            className="mx-3"
                            width="23"
                            height="22"
                            viewBox="0 0 13 12"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                fillRule="evenodd"
                                clipRule="evenodd"
                                d="M8.71143 7.54717H9.25345L12.6771 10.9777L11.6548 12L8.22429 8.57633V8.03431L8.03905 7.8422C7.25688 8.51458 6.24145 8.91938 5.13682 8.91938C2.67369 8.91938 0.677124 6.92281 0.677124 4.45969C0.677124 1.99657 2.67369 0 5.13682 0C7.59994 0 9.59651 1.99657 9.59651 4.45969C9.59651 5.56432 9.1917 6.57976 8.51932 7.36192L8.71143 7.54717ZM2.04933 4.4597C2.04933 6.16811 3.42841 7.54718 5.13681 7.54718C6.84522 7.54718 8.22429 6.16811 8.22429 4.4597C8.22429 2.7513 6.84522 1.37222 5.13681 1.37222C3.42841 1.37222 2.04933 2.7513 2.04933 4.4597Z"
                                fill="rgb(148 163 184 / 100%)"
                            />
                        </svg>
                        <input
                            type="text"
                            placeholder="Type here"
                            className="input rounded-none flex-auto bg-slate-700"
                        />
                    </div>
                </div>
                <div className="absolute bottom-5 right-5">
                    <QButton
                        onclick={setActiveState}
                        className={`absolute bottom-0 w-[68px] h-[68px] ease-in-out duration-300 ${
                            quickStatus === "none" || quickStatus === "quick"
                                ? "right-0 bg-quick-blue hover:bg-quick-blue border-quick-blue hover:border-quick-blue z-10"
                                : "right-3 bg-quick-disabled hover:bg-quick-disabled border-quick-disabled hover:border-quick-disabled z-0"
                        }`}>
                        <svg
                            width="18"
                            height="32"
                            viewBox="0 0 18 32"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                fillRule="evenodd"
                                clipRule="evenodd"
                                d="M12.4427 0.335868C13.3618 0.948573 13.6101 2.19031 12.9974 3.10937L5.73704 14H16C16.7376 14 17.4153 14.4059 17.7634 15.0563C18.1114 15.7066 18.0732 16.4957 17.6641 17.1094L8.33077 31.1094C7.71807 32.0284 6.47633 32.2768 5.55727 31.6641C4.63821 31.0514 4.38986 29.8096 5.00257 28.8906L12.263 18H2C1.26241 18 0.584692 17.594 0.236654 16.9437C-0.111384 16.2934 -0.0732391 15.5043 0.335902 14.8906L9.66924 0.890568C10.2819 -0.0284895 11.5237 -0.276837 12.4427 0.335868Z"
                                fill="white"
                            />
                        </svg>
                    </QButton>
                    <div
                        className={`text-center absolute bottom-0 ease-in-out duration-200 ${
                            quickStatus === "none"
                                ? "opacity-0 right-0 z-0"
                                : quickStatus === "inbox"
                                ? "opacity-100 right-0 z-20"
                                : quickStatus === "task"
                                ? "opacity-100 right-24 z-0"
                                : "opacity-100 right-24 z-0"
                        }`}>
                        <OpenBox
                            className={`absolute ease-in-out duration-300 -z-10 ${
                                quickStatus === "inbox"
                                    ? "opacity-100 bottom-20 right-0 max-w-[1000px] max-h-[1000px]"
                                    : "opacity-0 bottom-10 right-10 max-w-0 max-h-0"
                            }`}>
                            {quickStatus === "inbox" ? <ChatList /> : <></>}
                        </OpenBox>
                        <p
                            className={`font-bold ease-in-out duration-200 ${
                                quickStatus === "quick"
                                    ? "opacity-100"
                                    : "opacity-0"
                            }`}>
                            Inbox
                        </p>
                        <QButton
                            onclick={inboxOnclick}
                            className={`${
                                quickStatus === "inbox"
                                    ? "w-[68px] h-[68px] bg-quick-blue hover:bg-quick-blue border-quick-blue hover:border-quick-blue"
                                    : "w-[60px] h-[60px] bg-white hover:bg-white border-white hover:border-white"
                            }`}>
                            <svg
                                width="24"
                                height="23"
                                viewBox="0 0 24 23"
                                fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    fillRule="evenodd"
                                    clipRule="evenodd"
                                    d="M16.4443 0.110657H1.9999C1.38879 0.110657 0.888794 0.610657 0.888794 1.22177V16.7773L5.33324 12.3329H16.4443C17.0555 12.3329 17.5555 11.8329 17.5555 11.2218V1.22177C17.5555 0.610657 17.0555 0.110657 16.4443 0.110657ZM15.3332 2.3328V10.1106H4.41103L3.75547 10.7661L3.11103 11.4106V2.3328H15.3332ZM19.7777 4.55512H21.9999C22.611 4.55512 23.111 5.05512 23.111 5.66623V22.3329L18.6666 17.8885H6.44435C5.83324 17.8885 5.33324 17.3885 5.33324 16.7773V14.5551H19.7777V4.55512Z"
                                    fill={
                                        quickStatus === "inbox"
                                            ? "white"
                                            : "#8785FF"
                                    }
                                />
                            </svg>
                        </QButton>
                    </div>
                    <div
                        className={`text-center absolute bottom-0 ease-in-out duration-200 ${
                            quickStatus === "none"
                                ? "opacity-0 right-0 z-0"
                                : quickStatus === "task"
                                ? "opacity-100 right-0 z-20"
                                : quickStatus === "inbox"
                                ? "opacity-100 right-24 z-0"
                                : "opacity-100 right-44 z-0"
                        }`}>
                        <OpenBox
                            className={`absolute ease-in-out duration-300 -z-10 ${
                                quickStatus === "task"
                                    ? "opacity-100 bottom-20 right-0 10 max-w-[1000px] max-h-[1000px]"
                                    : "opacity-0 bottom-10 right-10 max-w-0 max-h-0"
                            }`}>
                            {quickStatus === "task" ? <TaskList /> : <></>}
                        </OpenBox>
                        <p
                            className={`font-bold ease-in-out duration-200 ${
                                quickStatus === "quick"
                                    ? "opacity-100"
                                    : "opacity-0"
                            }`}>
                            Task
                        </p>
                        <QButton
                            onclick={taskOnclick}
                            className={`${
                                quickStatus === "task"
                                    ? "w-[68px] h-[68px] bg-quick-orange hover:bg-quick-orange border-quick-orange hover:border-quick-orange"
                                    : "w-[60px] h-[60px] bg-white hover:bg-white border-white hover:border-white"
                            }`}>
                            <svg
                                width="26"
                                height="20"
                                viewBox="0 0 26 20"
                                fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path
                                    fillRule="evenodd"
                                    clipRule="evenodd"
                                    d="M3.11114 0.666687H23.1111C24.3334 0.666687 25.3334 1.66669 25.3334 2.88891V17.3334C25.3334 18.5556 24.3334 19.5556 23.1111 19.5556H3.11114C1.88892 19.5556 0.888916 18.5556 0.888916 17.3334V2.88891C0.888916 1.66669 1.88892 0.666687 3.11114 0.666687ZM3.11114 2.88891V17.3334H12V2.88891H3.11114ZM23.1111 17.3334H14.2222V2.88891H23.1111V17.3334ZM22 6.7778H15.3334V8.44446H22V6.7778ZM15.3334 9.55558H22V11.2222H15.3334V9.55558ZM22 12.3334H15.3334V14H22V12.3334Z"
                                    fill={
                                        quickStatus === "task"
                                            ? "white"
                                            : "#F8B76B"
                                    }
                                />
                            </svg>
                        </QButton>
                    </div>
                </div>
            </main>
        </div>
    );
}
